/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTranscriptsRouteImport } from './routes/_authenticated/transcripts'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated/schedule'
import { Route as AuthenticatedQuizzesRouteImport } from './routes/_authenticated/quizzes'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedLessonsRouteImport } from './routes/_authenticated/lessons'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAnnouncementsRouteImport } from './routes/_authenticated/announcements'
import { Route as AuthenticatedQuizzesIdRouteImport } from './routes/_authenticated/quizzes.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTranscriptsRoute =
  AuthenticatedTranscriptsRouteImport.update({
    id: '/transcripts',
    path: '/transcripts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQuizzesRoute = AuthenticatedQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLessonsRoute = AuthenticatedLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnnouncementsRoute =
  AuthenticatedAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQuizzesIdRoute = AuthenticatedQuizzesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedQuizzesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/lessons': typeof AuthenticatedLessonsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/quizzes': typeof AuthenticatedQuizzesRouteWithChildren
  '/schedule': typeof AuthenticatedScheduleRoute
  '/transcripts': typeof AuthenticatedTranscriptsRoute
  '/quizzes/$id': typeof AuthenticatedQuizzesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/lessons': typeof AuthenticatedLessonsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/quizzes': typeof AuthenticatedQuizzesRouteWithChildren
  '/schedule': typeof AuthenticatedScheduleRoute
  '/transcripts': typeof AuthenticatedTranscriptsRoute
  '/quizzes/$id': typeof AuthenticatedQuizzesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/announcements': typeof AuthenticatedAnnouncementsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/lessons': typeof AuthenticatedLessonsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/quizzes': typeof AuthenticatedQuizzesRouteWithChildren
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/_authenticated/transcripts': typeof AuthenticatedTranscriptsRoute
  '/_authenticated/quizzes/$id': typeof AuthenticatedQuizzesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/announcements'
    | '/dashboard'
    | '/lessons'
    | '/profile'
    | '/quizzes'
    | '/schedule'
    | '/transcripts'
    | '/quizzes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/announcements'
    | '/dashboard'
    | '/lessons'
    | '/profile'
    | '/quizzes'
    | '/schedule'
    | '/transcripts'
    | '/quizzes/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/announcements'
    | '/_authenticated/dashboard'
    | '/_authenticated/lessons'
    | '/_authenticated/profile'
    | '/_authenticated/quizzes'
    | '/_authenticated/schedule'
    | '/_authenticated/transcripts'
    | '/_authenticated/quizzes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/transcripts': {
      id: '/_authenticated/transcripts'
      path: '/transcripts'
      fullPath: '/transcripts'
      preLoaderRoute: typeof AuthenticatedTranscriptsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quizzes': {
      id: '/_authenticated/quizzes'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof AuthenticatedQuizzesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lessons': {
      id: '/_authenticated/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof AuthenticatedLessonsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/announcements': {
      id: '/_authenticated/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthenticatedAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quizzes/$id': {
      id: '/_authenticated/quizzes/$id'
      path: '/$id'
      fullPath: '/quizzes/$id'
      preLoaderRoute: typeof AuthenticatedQuizzesIdRouteImport
      parentRoute: typeof AuthenticatedQuizzesRoute
    }
  }
}

interface AuthenticatedQuizzesRouteChildren {
  AuthenticatedQuizzesIdRoute: typeof AuthenticatedQuizzesIdRoute
}

const AuthenticatedQuizzesRouteChildren: AuthenticatedQuizzesRouteChildren = {
  AuthenticatedQuizzesIdRoute: AuthenticatedQuizzesIdRoute,
}

const AuthenticatedQuizzesRouteWithChildren =
  AuthenticatedQuizzesRoute._addFileChildren(AuthenticatedQuizzesRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAnnouncementsRoute: typeof AuthenticatedAnnouncementsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLessonsRoute: typeof AuthenticatedLessonsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedQuizzesRoute: typeof AuthenticatedQuizzesRouteWithChildren
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
  AuthenticatedTranscriptsRoute: typeof AuthenticatedTranscriptsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnnouncementsRoute: AuthenticatedAnnouncementsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLessonsRoute: AuthenticatedLessonsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedQuizzesRoute: AuthenticatedQuizzesRouteWithChildren,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
  AuthenticatedTranscriptsRoute: AuthenticatedTranscriptsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
