/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated/schedule'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCoursesRouteImport } from './routes/_authenticated/courses'
import { Route as AuthenticatedBooksRouteImport } from './routes/_authenticated/books'
import { Route as AuthenticatedAssignmentsRouteImport } from './routes/_authenticated/assignments'
import { Route as AuthenticatedAnnouncementsRouteImport } from './routes/_authenticated/announcements'
import { Route as AuthenticatedLessonsIdRouteImport } from './routes/_authenticated/lessons.$id'
import { Route as AuthenticatedCoursesIdRouteImport } from './routes/_authenticated/courses.$id'
import { Route as AuthenticatedAttendanceScanRouteImport } from './routes/_authenticated/attendance.scan'
import { Route as AuthenticatedAssignmentsIdRouteImport } from './routes/_authenticated/assignments.$id'
import { Route as AuthenticatedAdminStudentsRouteImport } from './routes/_authenticated/admin.students'
import { Route as AuthenticatedAdminScheduleRouteImport } from './routes/_authenticated/admin.schedule'
import { Route as AuthenticatedAdminQuestionsRouteImport } from './routes/_authenticated/admin.questions'
import { Route as AuthenticatedAdminPointsRouteImport } from './routes/_authenticated/admin.points'
import { Route as AuthenticatedAdminCoursesRouteImport } from './routes/_authenticated/admin.courses'
import { Route as AuthenticatedAdminCertificatesRouteImport } from './routes/_authenticated/admin.certificates'
import { Route as AuthenticatedAdminBooksRouteImport } from './routes/_authenticated/admin.books'
import { Route as AuthenticatedAdminAttendanceRouteImport } from './routes/_authenticated/admin.attendance'
import { Route as AuthenticatedAdminAssignmentsRouteImport } from './routes/_authenticated/admin.assignments'
import { Route as AuthenticatedAdminAnnouncementsRouteImport } from './routes/_authenticated/admin.announcements'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCoursesRoute = AuthenticatedCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBooksRoute = AuthenticatedBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssignmentsRoute =
  AuthenticatedAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnnouncementsRoute =
  AuthenticatedAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLessonsIdRoute = AuthenticatedLessonsIdRouteImport.update({
  id: '/lessons/$id',
  path: '/lessons/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCoursesIdRoute = AuthenticatedCoursesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedCoursesRoute,
} as any)
const AuthenticatedAttendanceScanRoute =
  AuthenticatedAttendanceScanRouteImport.update({
    id: '/attendance/scan',
    path: '/attendance/scan',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssignmentsIdRoute =
  AuthenticatedAssignmentsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAssignmentsRoute,
  } as any)
const AuthenticatedAdminStudentsRoute =
  AuthenticatedAdminStudentsRouteImport.update({
    id: '/admin/students',
    path: '/admin/students',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminScheduleRoute =
  AuthenticatedAdminScheduleRouteImport.update({
    id: '/admin/schedule',
    path: '/admin/schedule',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminQuestionsRoute =
  AuthenticatedAdminQuestionsRouteImport.update({
    id: '/admin/questions',
    path: '/admin/questions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPointsRoute =
  AuthenticatedAdminPointsRouteImport.update({
    id: '/admin/points',
    path: '/admin/points',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCoursesRoute =
  AuthenticatedAdminCoursesRouteImport.update({
    id: '/admin/courses',
    path: '/admin/courses',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCertificatesRoute =
  AuthenticatedAdminCertificatesRouteImport.update({
    id: '/admin/certificates',
    path: '/admin/certificates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminBooksRoute = AuthenticatedAdminBooksRouteImport.update({
  id: '/admin/books',
  path: '/admin/books',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminAttendanceRoute =
  AuthenticatedAdminAttendanceRouteImport.update({
    id: '/admin/attendance',
    path: '/admin/attendance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAssignmentsRoute =
  AuthenticatedAdminAssignmentsRouteImport.update({
    id: '/admin/assignments',
    path: '/admin/assignments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAnnouncementsRoute =
  AuthenticatedAdminAnnouncementsRouteImport.update({
    id: '/admin/announcements',
    path: '/admin/announcements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/assignments': typeof AuthenticatedAssignmentsRouteWithChildren
  '/books': typeof AuthenticatedBooksRoute
  '/courses': typeof AuthenticatedCoursesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/assignments': typeof AuthenticatedAdminAssignmentsRoute
  '/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/admin/books': typeof AuthenticatedAdminBooksRoute
  '/admin/certificates': typeof AuthenticatedAdminCertificatesRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/points': typeof AuthenticatedAdminPointsRoute
  '/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/admin/schedule': typeof AuthenticatedAdminScheduleRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/assignments/$id': typeof AuthenticatedAssignmentsIdRoute
  '/attendance/scan': typeof AuthenticatedAttendanceScanRoute
  '/courses/$id': typeof AuthenticatedCoursesIdRoute
  '/lessons/$id': typeof AuthenticatedLessonsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/assignments': typeof AuthenticatedAssignmentsRouteWithChildren
  '/books': typeof AuthenticatedBooksRoute
  '/courses': typeof AuthenticatedCoursesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/assignments': typeof AuthenticatedAdminAssignmentsRoute
  '/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/admin/books': typeof AuthenticatedAdminBooksRoute
  '/admin/certificates': typeof AuthenticatedAdminCertificatesRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/points': typeof AuthenticatedAdminPointsRoute
  '/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/admin/schedule': typeof AuthenticatedAdminScheduleRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/assignments/$id': typeof AuthenticatedAssignmentsIdRoute
  '/attendance/scan': typeof AuthenticatedAttendanceScanRoute
  '/courses/$id': typeof AuthenticatedCoursesIdRoute
  '/lessons/$id': typeof AuthenticatedLessonsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/announcements': typeof AuthenticatedAnnouncementsRoute
  '/_authenticated/assignments': typeof AuthenticatedAssignmentsRouteWithChildren
  '/_authenticated/books': typeof AuthenticatedBooksRoute
  '/_authenticated/courses': typeof AuthenticatedCoursesRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/_authenticated/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/_authenticated/admin/assignments': typeof AuthenticatedAdminAssignmentsRoute
  '/_authenticated/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/_authenticated/admin/books': typeof AuthenticatedAdminBooksRoute
  '/_authenticated/admin/certificates': typeof AuthenticatedAdminCertificatesRoute
  '/_authenticated/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/_authenticated/admin/points': typeof AuthenticatedAdminPointsRoute
  '/_authenticated/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/_authenticated/admin/schedule': typeof AuthenticatedAdminScheduleRoute
  '/_authenticated/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/_authenticated/assignments/$id': typeof AuthenticatedAssignmentsIdRoute
  '/_authenticated/attendance/scan': typeof AuthenticatedAttendanceScanRoute
  '/_authenticated/courses/$id': typeof AuthenticatedCoursesIdRoute
  '/_authenticated/lessons/$id': typeof AuthenticatedLessonsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/announcements'
    | '/assignments'
    | '/books'
    | '/courses'
    | '/dashboard'
    | '/profile'
    | '/schedule'
    | '/admin/announcements'
    | '/admin/assignments'
    | '/admin/attendance'
    | '/admin/books'
    | '/admin/certificates'
    | '/admin/courses'
    | '/admin/points'
    | '/admin/questions'
    | '/admin/schedule'
    | '/admin/students'
    | '/assignments/$id'
    | '/attendance/scan'
    | '/courses/$id'
    | '/lessons/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/announcements'
    | '/assignments'
    | '/books'
    | '/courses'
    | '/dashboard'
    | '/profile'
    | '/schedule'
    | '/admin/announcements'
    | '/admin/assignments'
    | '/admin/attendance'
    | '/admin/books'
    | '/admin/certificates'
    | '/admin/courses'
    | '/admin/points'
    | '/admin/questions'
    | '/admin/schedule'
    | '/admin/students'
    | '/assignments/$id'
    | '/attendance/scan'
    | '/courses/$id'
    | '/lessons/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/announcements'
    | '/_authenticated/assignments'
    | '/_authenticated/books'
    | '/_authenticated/courses'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/_authenticated/schedule'
    | '/_authenticated/admin/announcements'
    | '/_authenticated/admin/assignments'
    | '/_authenticated/admin/attendance'
    | '/_authenticated/admin/books'
    | '/_authenticated/admin/certificates'
    | '/_authenticated/admin/courses'
    | '/_authenticated/admin/points'
    | '/_authenticated/admin/questions'
    | '/_authenticated/admin/schedule'
    | '/_authenticated/admin/students'
    | '/_authenticated/assignments/$id'
    | '/_authenticated/attendance/scan'
    | '/_authenticated/courses/$id'
    | '/_authenticated/lessons/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/courses': {
      id: '/_authenticated/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AuthenticatedCoursesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/books': {
      id: '/_authenticated/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof AuthenticatedBooksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assignments': {
      id: '/_authenticated/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AuthenticatedAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/announcements': {
      id: '/_authenticated/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthenticatedAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lessons/$id': {
      id: '/_authenticated/lessons/$id'
      path: '/lessons/$id'
      fullPath: '/lessons/$id'
      preLoaderRoute: typeof AuthenticatedLessonsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/courses/$id': {
      id: '/_authenticated/courses/$id'
      path: '/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof AuthenticatedCoursesIdRouteImport
      parentRoute: typeof AuthenticatedCoursesRoute
    }
    '/_authenticated/attendance/scan': {
      id: '/_authenticated/attendance/scan'
      path: '/attendance/scan'
      fullPath: '/attendance/scan'
      preLoaderRoute: typeof AuthenticatedAttendanceScanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assignments/$id': {
      id: '/_authenticated/assignments/$id'
      path: '/$id'
      fullPath: '/assignments/$id'
      preLoaderRoute: typeof AuthenticatedAssignmentsIdRouteImport
      parentRoute: typeof AuthenticatedAssignmentsRoute
    }
    '/_authenticated/admin/students': {
      id: '/_authenticated/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthenticatedAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/schedule': {
      id: '/_authenticated/admin/schedule'
      path: '/admin/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AuthenticatedAdminScheduleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/questions': {
      id: '/_authenticated/admin/questions'
      path: '/admin/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AuthenticatedAdminQuestionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/points': {
      id: '/_authenticated/admin/points'
      path: '/admin/points'
      fullPath: '/admin/points'
      preLoaderRoute: typeof AuthenticatedAdminPointsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/courses': {
      id: '/_authenticated/admin/courses'
      path: '/admin/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AuthenticatedAdminCoursesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/certificates': {
      id: '/_authenticated/admin/certificates'
      path: '/admin/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof AuthenticatedAdminCertificatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/books': {
      id: '/_authenticated/admin/books'
      path: '/admin/books'
      fullPath: '/admin/books'
      preLoaderRoute: typeof AuthenticatedAdminBooksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/attendance': {
      id: '/_authenticated/admin/attendance'
      path: '/admin/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AuthenticatedAdminAttendanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/assignments': {
      id: '/_authenticated/admin/assignments'
      path: '/admin/assignments'
      fullPath: '/admin/assignments'
      preLoaderRoute: typeof AuthenticatedAdminAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/announcements': {
      id: '/_authenticated/admin/announcements'
      path: '/admin/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AuthenticatedAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedAssignmentsRouteChildren {
  AuthenticatedAssignmentsIdRoute: typeof AuthenticatedAssignmentsIdRoute
}

const AuthenticatedAssignmentsRouteChildren: AuthenticatedAssignmentsRouteChildren =
  {
    AuthenticatedAssignmentsIdRoute: AuthenticatedAssignmentsIdRoute,
  }

const AuthenticatedAssignmentsRouteWithChildren =
  AuthenticatedAssignmentsRoute._addFileChildren(
    AuthenticatedAssignmentsRouteChildren,
  )

interface AuthenticatedCoursesRouteChildren {
  AuthenticatedCoursesIdRoute: typeof AuthenticatedCoursesIdRoute
}

const AuthenticatedCoursesRouteChildren: AuthenticatedCoursesRouteChildren = {
  AuthenticatedCoursesIdRoute: AuthenticatedCoursesIdRoute,
}

const AuthenticatedCoursesRouteWithChildren =
  AuthenticatedCoursesRoute._addFileChildren(AuthenticatedCoursesRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAnnouncementsRoute: typeof AuthenticatedAnnouncementsRoute
  AuthenticatedAssignmentsRoute: typeof AuthenticatedAssignmentsRouteWithChildren
  AuthenticatedBooksRoute: typeof AuthenticatedBooksRoute
  AuthenticatedCoursesRoute: typeof AuthenticatedCoursesRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
  AuthenticatedAdminAnnouncementsRoute: typeof AuthenticatedAdminAnnouncementsRoute
  AuthenticatedAdminAssignmentsRoute: typeof AuthenticatedAdminAssignmentsRoute
  AuthenticatedAdminAttendanceRoute: typeof AuthenticatedAdminAttendanceRoute
  AuthenticatedAdminBooksRoute: typeof AuthenticatedAdminBooksRoute
  AuthenticatedAdminCertificatesRoute: typeof AuthenticatedAdminCertificatesRoute
  AuthenticatedAdminCoursesRoute: typeof AuthenticatedAdminCoursesRoute
  AuthenticatedAdminPointsRoute: typeof AuthenticatedAdminPointsRoute
  AuthenticatedAdminQuestionsRoute: typeof AuthenticatedAdminQuestionsRoute
  AuthenticatedAdminScheduleRoute: typeof AuthenticatedAdminScheduleRoute
  AuthenticatedAdminStudentsRoute: typeof AuthenticatedAdminStudentsRoute
  AuthenticatedAttendanceScanRoute: typeof AuthenticatedAttendanceScanRoute
  AuthenticatedLessonsIdRoute: typeof AuthenticatedLessonsIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnnouncementsRoute: AuthenticatedAnnouncementsRoute,
  AuthenticatedAssignmentsRoute: AuthenticatedAssignmentsRouteWithChildren,
  AuthenticatedBooksRoute: AuthenticatedBooksRoute,
  AuthenticatedCoursesRoute: AuthenticatedCoursesRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
  AuthenticatedAdminAnnouncementsRoute: AuthenticatedAdminAnnouncementsRoute,
  AuthenticatedAdminAssignmentsRoute: AuthenticatedAdminAssignmentsRoute,
  AuthenticatedAdminAttendanceRoute: AuthenticatedAdminAttendanceRoute,
  AuthenticatedAdminBooksRoute: AuthenticatedAdminBooksRoute,
  AuthenticatedAdminCertificatesRoute: AuthenticatedAdminCertificatesRoute,
  AuthenticatedAdminCoursesRoute: AuthenticatedAdminCoursesRoute,
  AuthenticatedAdminPointsRoute: AuthenticatedAdminPointsRoute,
  AuthenticatedAdminQuestionsRoute: AuthenticatedAdminQuestionsRoute,
  AuthenticatedAdminScheduleRoute: AuthenticatedAdminScheduleRoute,
  AuthenticatedAdminStudentsRoute: AuthenticatedAdminStudentsRoute,
  AuthenticatedAttendanceScanRoute: AuthenticatedAttendanceScanRoute,
  AuthenticatedLessonsIdRoute: AuthenticatedLessonsIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
